# Generated by Django 6.0 on 2026-02-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
