# Generated by Django 4.2.29 on 2026-03-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_twin_plant_id', models.CharField(blank=True, default='', help_text='plant_id from MongoDB plant_profiles — links to a digital twin', max_length=64)),
                ('plant_name', models.CharField(max_length=120)),
                ('plant_type', models.CharField(choices=[('neem', 'Neem'), ('apple', 'Apple'), ('corn', 'Corn'), ('orange', 'Orange'), ('peach', 'Peach'), ('pepper', 'Pepper'), ('potato', 'Potato'), ('strawberry', 'Strawberry'), ('tomato', 'Tomato'), ('snake_plant', 'Snake Plant'), ('tulsi', 'Tulsi'), ('aloe_vera', 'Aloe Vera'), ('christmas_tree', 'Christmas Tree'), ('hibiscus', 'Hibiscus'), ('bougainvillea', 'Bougainvillea'), ('lavender', 'Lavender'), ('peony', 'Peony'), ('hydrangea', 'Hydrangea'), ('onion', 'Onion'), ('garlic', 'Garlic'), ('pineapple', 'Pineapple'), ('oats', 'Oats'), ('pot_marigold', 'Pot Marigold'), ('papaya', 'Papaya'), ('blue_cornflower', 'Blue Cornflower'), ('lemon', 'Lemon'), ('coffee_tree', 'Coffee Tree'), ('wild_carrot', 'Wild Carrot'), ('snowdrop', 'Snowdrop'), ('soyabean', 'Soyabean'), ('english_ivy', 'English Ivy'), ('hops', 'Hops'), ('lotus', 'Lotus'), ('yarrow', 'Yarrow'), ('feverfew', 'Feverfew'), ('oleander', 'Oleander'), ('oregano', 'Oregano'), ('avocado', 'Avocado'), ('beetroot', 'Beetroot'), ('vervain', 'Vervain'), ('money_plant', 'Money Plant'), ('banyan', 'Banyan'), ('purple_coneflower', 'Purple Coneflower'), ('basil', 'Basil'), ('rose', 'Rose'), ('custom', 'Custom / Other')], default='custom', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('base_water_days', models.PositiveSmallIntegerField(default=5)),
                ('base_fert_days', models.PositiveSmallIntegerField(default=30)),
                ('next_watering', models.DateField()),
                ('next_fertilize', models.DateField()),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('last_fertilized', models.DateTimeField(blank=True, null=True)),
                ('missed_waterings', models.PositiveSmallIntegerField(default=0)),
                ('health_score', models.SmallIntegerField(default=100)),
                ('current_weather', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('hot', 'Hot'), ('cold', 'Cold')], default='cloudy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_watering'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default='', help_text='With country code, e.g. +919876543210', max_length=20)),
                ('email_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('weather_location', models.CharField(blank=True, default='', help_text='City name or lat,lon for auto weather fetch', max_length=120)),
                ('current_weather', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('hot', 'Hot'), ('cold', 'Cold')], default='cloudy', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('urgent', 'Urgent'), ('upcoming', 'Upcoming'), ('informational', 'Informational')], max_length=20)),
                ('notif_type', models.CharField(choices=[('watering', 'Watering'), ('fertilize', 'Fertilize'), ('stress', 'Plant Stress'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='care_reminders.carereminder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
