# Generated by Django 4.2.29 on 2026-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forget_pass', '0002_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
