# Generated by Django 6.0 on 2026-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('soil_type', models.JSONField()),
                ('season', models.JSONField()),
                ('rainfall', models.JSONField()),
                ('humidity', models.JSONField()),
                ('sunlight', models.JSONField()),
            ],
        ),
    ]
